import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "sonner";
import AppProvider from "@/components/AppProvider";
import {ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<ClerkProvider afterSignOutUrl="/sign-in"
      appearance={{elements: {
          formButtonPrimary: "bg-primary hover:bg-primary/80 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer",
              }}}>
  <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster/>
      <SignedOut>

      <header className="flex justify-end items-center p-4 gap-4 h-16">
          {/* Show the sign-in and sign-up buttons when the user is signed out */}
              <SignInButton>
                  <Button className="" variant={"default"}>
                      Sign In
                  </Button>
              </SignInButton>
              <SignUpButton>
                  <Button className="" variant={"outline"}>
                      Sign Up
                  </Button>
              </SignUpButton>
      </header>
      </SignedOut>

      <AppProvider>
        {children}
        <Toaster />
      </AppProvider>

      </body>

    </html>
    </ClerkProvider>
  );
}
